version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: javaweb_db
      MYSQL_USER: javaweb_user
      MYSQL_PASSWORD: javaweb_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
